version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  test:
    working_directory: ~/project-name
    docker:
      - image: circleci/node:10-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # # Lint the source code
      # - run:
      #     name: Linting
      #     command: npm run lint
      # Test the source code
      - run:
          name: Testing
          command: npm run frontend:unittest -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      # End to End test
      - run:
          name: End to End Test
          command: npm run frontend:e2etest -- --protractor-config=e2e/protractor-ci.conf.js
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
workflows:
  udagram:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - main
                - master
